version: "3.0"
services:
  apache:
    build: 
      context: .
      dockerfile: dockerfiles/apache_php.dockerfile
    container_name: qwavee-apache_php-container
    ports:
      - 80:80
    depends_on:
      - db      
    volumes:
      - ./www:/var/www/html/
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled/

  db:
    image: mysql/mysql-server:5.7.21
    restart: always
    container_name: qwavee-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database    
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

   