version: "3"
services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: qwavee-sqlserver-container
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Qwavee!321
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    networks:
      qwavee-network:
    volumes:
      - ./mssql:/var/opt/mssql/

networks:
  qwavee-network:
    external:
      name: qwavee-docker-network
