version: "3.0"
services:
  redis:
    image: redis:alpine
    container_name: qwavee-redis-container
    ports:
      - "6379:6379"
    networks:
      qwavee-network

networks:
  qwavee-network:
    external:
      name: qwavee-docker-network